### ISSUE TITLE
Uploading a CSV file from myOswego results in quotation marks to be added to student names

### ISSUE THREAD

**Issue by tenbergen** [tenbergen/CSC480-22S#253]
I download a CSV file from myOswego and I noticed that in the roster section, every string has " added before and after. Even in email addresses. This might mean some people can't log in.

**Comment by lunarmint** [comment]
Confirmed to be a parse issue.

**Comment by lunarmint** [comment]
We talked briefly about this but I will leave it here again for future reference. Apparently that a touched CSV file using Microsoft Excel would break the format of the file in a strange way that would make all the strings come with an extra pair of quotation mark.

A rewrite on the parsing algorithm is currently under development to make it more dynamic and efficient, hopefully it will alleviate the issue.

**Comment by asigdel29** [comment]
Fixed in the first sprint
