### ISSUE TITLE
Unable to Access Courses with CPR Tool

### ISSUE THREAD

**Issue by MatthewDBrown50** [tenbergen/CSC480-22S#255]
I have attempted to troubleshoot the CPR Tool on both my laptop and my desktop PC, to no avail. I tried it with both Chrome and Firefox on each device.

When I try to log in to my account in Chrome, the login window disappears after I've entered my credentials, but does not proceed beyond the 'welcome' screen. Refreshing the page does not help. Closing and re-opening the browser does not help.

When I log in with Firefox, it accepts my credentials and brings me to my home page, but it is blank. When clicking on the "Courses" button, it is completely unresponsive. Refreshing the page does not help. Closing and re-opening the browser does not help.

In each case, I made sure to use my school account (mbrown50@oswego.edu), not my personal account.

**Comment by lunarmint** [comment]
From what I found out, apparently this is a server-side issue. The server that the app ran on has an ongoing networking issue where it would need to reboot (multiple times a day sometimes, even), which means that all services will be unavailable temporarily and what you see on the browser is likely being rendered from cache. Unfortunate timing, perhaps? Multiple docker containers for the same service was also being ran accidentally which also might have led to some networking conflict on the back end side too.

Those are just educated guesses though. Things are working again for now, but please let me know if it happens again in the future (and I can re-open this issue and look into it!).
