### ISSUE TITLE
Successful HTTP requests are being unnecessarily logged in console

### ISSUE THREAD

**Issue by lunarmint** [tenbergen/CSC480-22S#266]
Not necessarily a bug, but it's usually better to do server-side log rather than client-side log for production code, as this increases the size of javascript being sent to user, which might lead to increased response time.

**Comment by logann131** [comment]
Hey Mint,
Our front-end team last semester logged things out to confirm the requests and seems like they forgot to remove them. Considered an easy fix and I will get on removing them soon.
Thanks for the issue

Cheers,
Logan

**Comment by lunarmint** [comment]
> Hey Mint,
> 
> Our front-end team last semester logged things out to confirm the requests and seems like they forgot to remove them. Considered an easy fix and I will get on removing them soon.
> 
> Thanks for the issue
> 
> 
> 
> Cheers,
> 
> Logan

I wonder if there are any good server-side logging module that could be used with React before we remove them? I figured that it might make future debugging attemps a bit less of a headache.
