### ISSUE TITLE
professor team composition

### ISSUE THREAD

**Issue by tenbergen** [tenbergen/CSC480-22S#276]
PRofessors need the additional ability to:
- create teams on behalf of the students (currently can't create teams)
- add students to existing teams from a list (currently need to enter user ID, which is the lakerID before the @oswego.edu and type it in)

**Comment by logann131** [comment]
Confirm requirements and will be working on adding these feature soon.

**Comment by tenbergen** [comment]
not urgent. can leave it for Spring '23.

**Comment by asigdel29** [comment]
Instructor elevated privileges 
- create teams on behalf of students , the professor cannot create empty teams and hence has to add one student to the team 
- Add existing students to the team (including checks for team size)
