### ISSUE TITLE
setting team sizes and class roster upon course creation should be possible.

### ISSUE THREAD

**Issue by tenbergen** [tenbergen/CSC480-22S#277]
right now, i have to create a course with most information, but then have to enter the course, click "manage" and set a team size and upload a roster then. would be nice to have it available to optionally add in the first step already.

**Comment by logann131** [comment]
Confirm requirements and will be working on adding this feature soon.

**Comment by tenbergen** [comment]
not urgent. can leave for Spring '23

**Comment by asigdel29** [comment]
When creating a course you can now upload roster for mass adding students and set team size
