### ISSUE TITLE
creating an assignment without peer review part

### ISSUE THREAD

**Issue by tenbergen** [tenbergen/CSC480-22S#279]
peer review parts are required when creating assignments. should be possible to only create an assignment, then update peer review parts later.

will probably need some checks to make sure peer review can't be initiated when there's stuff missing.

**Comment by asigdel29** [comment]
After the new release from Spring 2023, you can create assignments that do not include peer review component , you can go into assignment details as a professor to update peer review parts later,

you can't initiate peer reviews if the due date is before assignment due date , the template, rubric and instructions are mandatory to put in along with maximum points
