### ISSUE TITLE
looking at student submissions, they're displayed anonymously.

### ISSUE THREAD

**Issue by tenbergen** [tenbergen/CSC480-22S#284]
see screen shot.
<img width="2560" alt="Screen Shot 2022-09-09 at 09 19 42 (2)" src="https://user-images.githubusercontent.com/16921732/189359430-daf4a866-5201-4878-9851-2aff4048468d.png">

**Comment by tenbergen** [comment]
there's also no "back" button.

**Comment by Kayyali78** [comment]
Fixed - Changed Assignment submissions to be named by team
