### ISSUE TITLE
tool doesn't allow uploading reviews for assigned teams, but different ones.

### ISSUE THREAD

**Issue by tenbergen** [tenbergen/CSC480-22S#300]
Team Ostrich in 22F was assigned Vu00Ma01, Co98Bi01, Mi01
but CPR tool only allows submitting for teams: Vu00Ma01, OhNoAnotherBug, Ei00Ca02

**Comment by lunarmint** [comment]
This is due to testing session on the distribution algorithm which led to the teams being re-shuffled. However, a snapshot of the database was recorded and recovered to that point in time. It should work correctly (again) now. My apologies!
