### ISSUE TITLE
issues submitting documents

### ISSUE THREAD

**Issue by tenbergen** [tenbergen/CSC480-22S#303]
The documents that our team are supposed to grade show up as downloadable but it isn't set for a particular file such as a pdf or a docx file like the grading template is or the calibrated-soilutions.zip. This is from the CPR Tool that is. When I downloaded the files to my computer and tried to open them anywhere it just popped up with a bunch of boxes of text.
![CRPTool](https://user-images.githubusercontent.com/16921732/190654929-cd3dad68-4a1d-4cbd-a4aa-4221eeebe128.PNG)

**Comment by Kayyali78** [comment]
Fixed. Files changed to save as Base64 with file extensions included
